<?xml version="1.0"?>
<package format="3">
  <name>drivetrain_bringup</name>
  <version>1.1.0</version>
  <description>
    Top-level bringup for the UWRobotics Sparky drivetrain. 
  </description>
  <author>UWRobotics Team</author>
  <maintainer email="uwaterloorobotics@gmail.com">UWRobotics Team</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>sparky_description</exec_depend>
  <exec_depend>groundstation_bringup</exec_depend>
  <exec_depend>servo_control</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
