<?xml version="1.0"?>
<package format="3">
  <name>groundstation_bringup</name>
  <version>1.1.0</version>
  <description>
    Ground station bringup for the UWRobotics Sparky rover.
  </description>
  <author>UWRobotics Team</author>
  <maintainer email="uwaterloorobotics@gmail.com">UWRobotics Team</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>akros2_teleop</exec_depend>
  <exec_depend>gimbal_teleop</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>siyi_ros2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
