<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arm_teleop</name>
  <version>0.0.1</version>
  <description>Xbox 360 controller teleoperation for the Sparky 6DOF arm</description>
  <maintainer email="todo@uwrobotics.ca">UWRobotics</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>odrive_can</depend>
  <depend>joy_linux</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>