controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    position_controller:
      type: position_controllers/JointGroupPositionController

forward_velocity_controller:
  ros__parameters:
    joints:
      - Joint_4
    interface_name: velocity

position_controller:
  ros__parameters: 
    joints:
       - Joint_1
       - Joint_2
       - Joint_3
       - Joint_5
       - Joint_6